# Generated by Django 5.1.4 on 2025-01-06 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_comments_liked_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post_liked',
            new_name='posts_liked',
        ),
    ]
